# Kafka Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ledger-dev

resources:
  - kafka-configmap.yaml
  - kafka-service.yaml
  - kafka-statefulset.yaml

commonLabels:
  app.kubernetes.io/name: kafka
  app.kubernetes.io/part-of: double-entry-ledger
  environment: dev
