apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ledger-core

namespace: ledger-dev

commonLabels:
  app.kubernetes.io/name: ledger-core
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: double-entry-ledger
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
