apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kafka-ui

namespace: ledger-dev

commonLabels:
  app.kubernetes.io/name: kafka-ui
  app.kubernetes.io/component: observability
  app.kubernetes.io/part-of: double-entry-ledger
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
